Food Picker

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df1 = pd.read_csv(r"dataset-ayam.csv")
df2 = pd.read_csv(r"dataset-ikan.csv")
df3 = pd.read_csv(r"dataset-kambing.csv")
df4 = pd.read_csv(r"dataset-sapi.csv")
df5 = pd.read_csv(r"dataset-tahu.csv")
df6 = pd.read_csv(r"dataset-telur.csv")
df7 = pd.read_csv(r"dataset-tempe.csv")
df8 = pd.read_csv(r"dataset-udang.csv")

In [ ]:
df_list = [df1, df2, df3, df4, df5, df6, df7, df8]
df = pd.concat(df_list, ignore_index=True)
df.reset_index()
df['index'] = df.index
display(df)

Title  ...  index
0                       Ayam Woku Manado  ...      0
1               Ayam goreng tulang lunak  ...      1
2                       Ayam cabai kawin  ...      2
3                            Ayam Geprek  ...      3
4                            Minyak Ayam  ...      4
...                                  ...  ...    ...
15636                 Udang saus mentega  ...  15636
15637                 Jipang tumis udang  ...  15637
15638                  Tumis Udang Tempe  ...  15638
15639  Tumis kacang panjang terong udang  ...  15639
15640                  Siomay Udang Ayam  ...  15640

[15641 rows x 6 columns]

In [ ]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["Ingredients"].values.astype('U'))
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
cosine_sim = cosine_similarity(count_matrix)
cosine_sim

array([[1.        , 0.33088308, 0.37876284, ..., 0.3453896 , 0.32153676,
        0.22913326],
       [0.33088308, 1.        , 0.33136138, ..., 0.14421499, 0.02685108,
        0.32289629],
       [0.37876284, 0.33136138, 1.        , ..., 0.61316662, 0.4149429 ,
        0.36962033],
       ...,
       [0.3453896 , 0.14421499, 0.61316662, ..., 1.        , 0.52553026,
        0.28087721],
       [0.32153676, 0.02685108, 0.4149429 , ..., 0.52553026, 1.        ,
        0.08541668],
       [0.22913326, 0.32289629, 0.36962033, ..., 0.28087721, 0.08541668,
        1.        ]])

In [ ]:
recipe_user_likes = "Siomay Udang Ayam"
def get_index_from_title(Title):
    return df[df.Title == Title]["index"].values[0]
recipe_index = get_index_from_title(recipe_user_likes)
recipe_index

15640

In [ ]:
similar_recipes = list(enumerate(cosine_sim[recipe_index]))
similar_recipes

[(0, 0.22913326005048196),
 (1, 0.3228962894335844),
 (2, 0.3696203327805406),
 (3, 0.3614468324789002),
 (4, 0.2730094531159741),
 (5, 0.17788889798987031),
 (6, 0.31277162108561213),
 (7, 0.3620824200783102),
 (8, 0.45566634985115917),
 (9, 0.5253446549616276),
 (10, 0.33341566835579034),
 (11, 0.41702882811414954),
 (12, 0.16084970334678367),
 (13, 0.3693743065316841),
 (14, 0.3334156683557903),
 (15, 0.34452952396765),
 (16, 0.22074603860391706),
 (17, 0.29401532747073544),
 (18, 0.28552012036008034),
 (19, 0.3614468324789002),
 (20, 0.5874275513035242),
 (21, 0.5060894014039801),
 (22, 0.26420969566808894),
 (23, 0.22146989195707453),
 (24, 0.2347564750830957),
 (25, 0.3014690539057585),
 (26, 0.19937791451169073),
 (27, 0.4859836666222461),
 (28, 0.2781469555832955),
 (29, 0.4297147093803056),
 (30, 0.2919201796799047),
 (31, 0.20295302744752153),
 (32, 0.4114406565333951),
 (33, 0.29576024087563857),
 (34, 0.14764659463804966),
 (35, 0.3039593794371644),
 (36, 0.3686048903872428

In [ ]:
sorted_similar_recipes = sorted(similar_recipes, key=lambda x:x[1], reverse=True)
sorted_similar_recipes

[(15640, 1.0000000000000002),
 (13104, 0.7450760631780817),
 (14212, 0.7313574508612275),
 (15360, 0.719870728700614),
 (12995, 0.7168795835326197),
 (14463, 0.7088695043765847),
 (1807, 0.7082882469748284),
 (1392, 0.6982379478974613),
 (12781, 0.6969627833961297),
 (13249, 0.6919952095899509),
 (1153, 0.6872846924289854),
 (7392, 0.6862551498591694),
 (13216, 0.6861496659066958),
 (5936, 0.6857971462119892),
 (14302, 0.685782969380264),
 (13336, 0.6843364477565328),
 (13090, 0.6836602258050605),
 (9112, 0.6826658104048073),
 (497, 0.6813598225089801),
 (161, 0.6805179756979312),
 (13059, 0.679438612859544),
 (14604, 0.679438612859544),
 (3476, 0.6784657932790075),
 (12674, 0.6756639246921763),
 (7009, 0.6743086892153103),
 (1010, 0.6729046193285273),
 (7159, 0.6724387801454331),
 (7818, 0.6715507368448513),
 (1473, 0.6697108225289158),
 (616, 0.6682951125722248),
 (15291, 0.6677805632941778),
 (14191, 0.6677299105415511),
 (14472, 0.6675718492514822),
 (6245, 0.667325103041149),
 (60

In [ ]:
def get_title_from_index(index):
    return df[df.index == index]["Title"].values[0]
i=0
for recipe in sorted_similar_recipes:
    print(get_title_from_index(recipe[0]))
    i=i+1
    if i>10:
        break

Siomay Udang Ayam
Tempe mendoan
Bakso Ayung (Ayam+Udang)
Udang butterfly
Bakso Tempe Saus Tiram
Siomay ayam udang
Nugget ayam simple
Nugget Ayam
Tempe goreng sederhana
Tempe Mendoan
Manuka honey lemon Chicken
